/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressDialog: typeof import('./components/address/AddressDialog.vue')['default']
    AddressForm: typeof import('./components/address/AddressForm.vue')['default']
    AddressForma: typeof import('./components/address/AddressForma.vue')['default']
    AddressPreview: typeof import('./components/address/AddressPreview.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputText: typeof import('./components/inputs/InputText.vue')['default']
    Pagination: typeof import('./components/pagination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/inputs/Search.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    Table: typeof import('./components/table/Table.vue')['default']
    TitleSection: typeof import('./components/ui/TitleSection.vue')['default']
  }
}
